=== EmilianStankov/Collage/data/collage.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://collage.com"
xmlns="http://collage.com"
elementFormDefault="qualified">

<xs:element name="collage">
  <xs:complexType>
    <xs:choice maxOccurs="unbounded">
      <xs:element name="image">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="source" type="xs:string"/>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="position-x" type="xs:integer"/>
            <xs:element name="position-y" type="xs:integer"/>
            <xs:element name="width" type="xs:integer"/>
            <xs:element name="height" type="xs:integer"/>
            <xs:element name="rotation" type="xs:integer"/>
            <xs:element name="alpha" type="xs:integer"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:choice>
  </xs:complexType>
</xs:element>

</xs:schema>

=== EmilianStankov/Collage/data/collage2.xml
<?xml version="1.0" encoding="UTF-8"?>
<collage
xmlns="http://collage.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://collage.com collage.xsd">
  <image>
    <source>data/images/photo3.jpg</source>
    <title>a</title>
    <position-x>120</position-x>
    <position-y>145</position-y>
    <width>200</width>
    <height>100</height>
    <rotation>70</rotation>
    <alpha>20</alpha>
  </image>
  <image>
    <source>data/images/photo6.jpg</source>
    <title>b</title>
    <position-x>150</position-x>
    <position-y>10</position-y>
    <width>250</width>
    <height>110</height>
    <rotation>12</rotation>
    <alpha>50</alpha>
  </image>
  <image>
    <source>data/images/photo4.jpg</source>
    <title>c</title>
    <position-x>0</position-x>
    <position-y>200</position-y>
    <width>300</width>
    <height>55</height>
    <rotation>4</rotation>
    <alpha>100</alpha>
  </image>
</collage>

=== EmilianStankov/Collage/data/collage1.xml
<?xml version="1.0" encoding="UTF-8"?>
<collage
xmlns="http://collage.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://collage.com collage.xsd">
  <image>
    <source>data/images/photo1.jpg</source>
    <title>road</title>
    <position-x>50</position-x>
    <position-y>10</position-y>
    <width>100</width>
    <height>50</height>
    <rotation>21</rotation>
    <alpha>100</alpha>
  </image>
  <image>
    <source>data/images/photo2.jpg</source>
    <title>castle</title>
    <position-x>150</position-x>
    <position-y>10</position-y>
    <width>200</width>
    <height>100</height>
    <rotation>0</rotation>
    <alpha>50</alpha>
  </image>
  <image>
    <source>data/images/photo3.jpg</source>
    <title>forest</title>
    <position-x>0</position-x>
    <position-y>100</position-y>
    <width>100</width>
    <height>50</height>
    <rotation>0</rotation>
    <alpha>75</alpha>
  </image>
</collage>
